-- ==============================================================================
-- DEV FIT - CATALOGO COMPLETO ESERCIZI (SEED AUTOSUFFICIENTE PER SUPABASE)
-- 51 esercizi ricchi di informazioni tecniche, muscoli e consigli di esecuzione
-- Esegui questo script in una NUOVA SCHEDA dell'SQL Editor di Supabase
-- ==============================================================================

-- 1. Assicura che la tabella exercises esista
CREATE TABLE IF NOT EXISTS public.exercises (
  id text PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL DEFAULT 'Altro',
  muscle_group text NOT NULL DEFAULT 'Altro',
  secondary_muscles text[] DEFAULT '{}',
  equipment text NOT NULL DEFAULT 'Niente',
  tracking_type text NOT NULL DEFAULT 'weight_reps',
  instructions text DEFAULT '',
  execution_tips text DEFAULT '',
  video_url text DEFAULT '',
  is_custom boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES auth.users ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. Assicura che TUTTE le colonne esistano (garantisce secondary_muscles e tracking_type)
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'Altro';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS muscle_group text NOT NULL DEFAULT 'Altro';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS secondary_muscles text[] DEFAULT '{}';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS equipment text NOT NULL DEFAULT 'Niente';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS tracking_type text NOT NULL DEFAULT 'weight_reps';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS instructions text DEFAULT '';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS execution_tips text DEFAULT '';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS video_url text DEFAULT '';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS is_custom boolean NOT NULL DEFAULT false;
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users ON DELETE CASCADE;

-- 3. RLS e permessi
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read system exercises and own custom exercises" ON public.exercises;
CREATE POLICY "Anyone can read system exercises and own custom exercises"
  ON public.exercises FOR SELECT
  USING (is_custom = false OR auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can insert their own custom exercises" ON public.exercises;
CREATE POLICY "Users can insert their own custom exercises"
  ON public.exercises FOR INSERT
  WITH CHECK (is_custom = true AND auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can update their own custom exercises" ON public.exercises;
CREATE POLICY "Users can update their own custom exercises"
  ON public.exercises FOR UPDATE
  USING (auth.uid() = created_by)
  WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can delete their own custom exercises" ON public.exercises;
CREATE POLICY "Users can delete their own custom exercises"
  ON public.exercises FOR DELETE
  USING (auth.uid() = created_by);

CREATE INDEX IF NOT EXISTS idx_exercises_custom ON public.exercises(is_custom, created_by);
CREATE INDEX IF NOT EXISTS idx_exercises_muscle ON public.exercises(muscle_group);

-- 4. Inserimento atomico dei 51 esercizi ufficiali DeV Fit
BEGIN;

INSERT INTO public.exercises (
  id,
  name,
  category,
  muscle_group,
  secondary_muscles,
  equipment,
  tracking_type,
  instructions,
  execution_tips,
  video_url,
  is_custom
) VALUES
  ('ex-panca-declinata-bil',
  'Panca Declinata con Bilanciere',
  'Petto',
  'Pettorali',
  ARRAY['Tricipiti', 'Spalle'],
  'Bilanciere',
  'weight_reps',
  'Panca inclinata verso il basso a -15°/-30°. Abbassa il bilanciere alla parte inferiore del petto per enfatizzare il fascio sternocostale.',
  'Adduci e deprimi le scapole prima di iniziare. Tieni i gomiti a circa 45° rispetto al busto per proteggere le spalle. Espira in spinta.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-bench-press-with-barbell-close-up-40321-large.mp4',
  false),
  ('ex-pectoral-machine',
  'Pectoral Machine (Pec Deck)',
  'Petto',
  'Pettorali',
  ARRAY['Tricipiti', 'Spalle'],
  'Macchina',
  'weight_reps',
  'Posiziona gli avambracci o le mani sui cuscinetti. Chiudi le braccia davanti a te focalizzando la massima spremuta al centro del petto.',
  'Adduci e deprimi le scapole prima di iniziare. Tieni i gomiti a circa 45° rispetto al busto per proteggere le spalle. Espira in spinta.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-his-chest-at-the-gym-flat-40337-large.mp4',
  false),
  ('ex-piegamenti',
  'Piegamenti sulle Braccia (Push-Up)',
  'Petto',
  'Pettorali',
  ARRAY['Tricipiti', 'Spalle'],
  'Niente',
  'weight_reps',
  'Corpo dritto in plank, mani leggermente più larghe delle spalle. Scendi sfiorando il pavimento con il petto e distendi con forza.',
  'Adduci e deprimi le scapole prima di iniziare. Tieni i gomiti a circa 45° rispetto al busto per proteggere le spalle. Espira in spinta.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-dip-parallele',
  'Dip alle Parallele per Petto',
  'Petto',
  'Pettorali',
  ARRAY['Tricipiti', 'Spalle'],
  'Niente',
  'weight_reps',
  'Inclinati in avanti con il busto a circa 30° e allarga leggermente i gomiti per concentrare il carico sul petto inferiore.',
  'Adduci e deprimi le scapole prima di iniziare. Tieni i gomiti a circa 45° rispetto al busto per proteggere le spalle. Espira in spinta.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-bench-press-with-barbell-close-up-40321-large.mp4',
  false),
  ('ex-lat-machine',
  'Lat Pulldown al Cavo (Presa Larga)',
  'Dorso',
  'Dorsali',
  ARRAY['Bicipiti', 'Spalle'],
  'Cavi',
  'weight_reps',
  'Tira la sbarra verso la parte alta del petto portando i gomiti verso il basso e indietro, aprendo la cassa toracica.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-on-lat-pull-down-machine-40336-large.mp4',
  false),
  ('ex-trazioni-sbarra',
  'Trazioni alla Sbarra (Pull-Up)',
  'Dorso',
  'Dorsali',
  ARRAY['Bicipiti', 'Spalle'],
  'Niente',
  'weight_reps',
  'Presa prona oltre la larghezza spalle. Sollevati fino a superare la sbarra con il mento senza dondolare.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-on-lat-pull-down-machine-40336-large.mp4',
  false),
  ('ex-chin-ups',
  'Trazioni Presa Supina (Chin-Up)',
  'Dorso',
  'Dorsali',
  ARRAY['Bicipiti', 'Spalle'],
  'Niente',
  'weight_reps',
  'Palmi verso il viso. Sollevati stringendo dorsali e bicipiti con massima escursione di movimento.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-on-lat-pull-down-machine-40336-large.mp4',
  false),
  ('ex-t-bar-row',
  'T-Bar Row con Supporto',
  'Dorso',
  'Dorsali',
  ARRAY['Bicipiti', 'Spalle'],
  'Macchina',
  'weight_reps',
  'Petto appoggiato al cuscinetto. Tira le maniglie verso di te per isolare lo spessore dorsale e i romboidi.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-on-lat-pull-down-machine-40336-large.mp4',
  false),
  ('ex-pullover-cavo',
  'Pullover al Cavo Alto con Corda',
  'Dorso',
  'Dorsali',
  ARRAY['Bicipiti', 'Spalle'],
  'Cavi',
  'weight_reps',
  'Braccia quasi tese, busto inclinato a 30°. Abbassa la corda verso le cosce ad arco contraendo i dorsali.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-on-lat-pull-down-machine-40336-large.mp4',
  false),
  ('ex-stacco-terra',
  'Stacco da Terra Tradizionale (Deadlift)',
  'Dorso',
  'Lombari',
  ARRAY['Bicipiti', 'Spalle'],
  'Bilanciere',
  'weight_reps',
  'Piedi larghezza anche, schiena neutra. Spingi via il pavimento estendendo contemporaneamente ginocchia e anche.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-scrollate-bil',
  'Scrollate con Bilanciere (Shrug)',
  'Dorso',
  'Trapezi',
  ARRAY['Bicipiti', 'Spalle'],
  'Bilanciere',
  'weight_reps',
  'Braccia tese lungo i fianchi. Solleva le spalle dritto verso le orecchie, trattieni 1 secondo e rilascia.',
  'Inizia il movimento tirando i gomiti verso i fianchi, non tirare solo di braccia. Concentrati sulla contrazione dorsale.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-exercising-on-lat-pull-down-machine-40336-large.mp4',
  false),
  ('ex-alzate-laterali-cavo',
  'Alzate Laterali al Cavo Singolo',
  'Spalle',
  'Spalle',
  ARRAY['Tricipiti', 'Trapezi'],
  'Cavi',
  'weight_reps',
  'Cavo basso che passa dietro il corpo o davanti. Tensione costante su tutto il range del deltoide laterale.',
  'Evita di inarcare la zona lombare stringendo i glutei. Movimento controllato sia in salita che in discesa.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-dumbbell-lateral-raises-40333-large.mp4',
  false),
  ('ex-alzate-frontali-manubri',
  'Alzate Frontali con Manubri',
  'Spalle',
  'Spalle',
  ARRAY['Tricipiti', 'Trapezi'],
  'Manubri',
  'weight_reps',
  'Solleva un manubrio alla volta dritto davanti a te fino al livello degli occhi, isolando il deltoide anteriore.',
  'Evita di inarcare la zona lombare stringendo i glutei. Movimento controllato sia in salita che in discesa.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-dumbbell-lateral-raises-40333-large.mp4',
  false),
  ('ex-alzate-frontali-disco',
  'Alzate Frontali con Disco',
  'Spalle',
  'Spalle',
  ARRAY['Tricipiti', 'Trapezi'],
  'Disco',
  'weight_reps',
  'Afferra un disco olimpico a ore 9 e ore 3. Sollevalo davanti al viso mantenendo le braccia tese.',
  'Evita di inarcare la zona lombare stringendo i glutei. Movimento controllato sia in salita che in discesa.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-dumbbell-lateral-raises-40333-large.mp4',
  false),
  ('ex-alzate-posteriori',
  'Alzate Posteriori a 90° con Manubri',
  'Spalle',
  'Spalle',
  ARRAY['Tricipiti', 'Trapezi'],
  'Manubri',
  'weight_reps',
  'Busto flesso a 90° con schiena piatta. Apri le braccia a croce concentrandoti sui deltoidi posteriori.',
  'Evita di inarcare la zona lombare stringendo i glutei. Movimento controllato sia in salita che in discesa.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-dumbbell-lateral-raises-40333-large.mp4',
  false),
  ('ex-curl-bilanciere',
  'Curl Bicipiti con Bilanciere',
  'Braccia',
  'Bicipiti',
  ARRAY['Avambracci'],
  'Bilanciere',
  'weight_reps',
  'Gomiti saldi ai fianchi. Fletti le braccia sollevando il bilanciere verso le spalle senza oscillare con il busto.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-man-doing-biceps-curls-with-dumbbells-40328-large.mp4',
  false),
  ('ex-curl-scott',
  'Curl alla Panca Scott (Preacher Curl)',
  'Braccia',
  'Bicipiti',
  ARRAY['Avambracci'],
  'Bilanciere',
  'weight_reps',
  'Braccia bloccate sul cuscinetto inclinato della panca Scott per impedire qualsiasi cheating con le spalle.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-man-doing-biceps-curls-with-dumbbells-40328-large.mp4',
  false),
  ('ex-curl-cavi-basso',
  'Curl Bicipiti al Cavo Basso',
  'Braccia',
  'Bicipiti',
  ARRAY['Avambracci'],
  'Cavi',
  'weight_reps',
  'Tensione elastica costante anche nella parte inferiore del movimento, ideale per un pompaggio continuo.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-man-doing-biceps-curls-with-dumbbells-40328-large.mp4',
  false),
  ('ex-curl-21',
  'Curl Bicipiti 21',
  'Braccia',
  'Bicipiti',
  ARRAY['Avambracci'],
  'Bilanciere',
  'weight_reps',
  '7 ripetizioni dal basso a metà, 7 da metà fino in cima, e 7 ripetizioni con arco di movimento completo.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-man-doing-biceps-curls-with-dumbbells-40328-large.mp4',
  false),
  ('ex-pushdown-barra',
  'Pushdown Tricipiti con Barra a V',
  'Braccia',
  'Tricipiti',
  ARRAY['Avambracci'],
  'Cavi',
  'weight_reps',
  'Presa solida sulla barra a V. Distendi le braccia spingendo verso il basso senza alzare le spalle.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-performing-triceps-pushdown-at-the-gym-40335-large.mp4',
  false),
  ('ex-pushdown-singolo',
  'Pushdown Tricipiti a Braccio Singolo',
  'Braccia',
  'Tricipiti',
  ARRAY['Avambracci'],
  'Cavi',
  'weight_reps',
  'Lavora un braccio per volta per correggere asimmetrie muscolari e garantire una contrazione focalizzata.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-performing-triceps-pushdown-at-the-gym-40335-large.mp4',
  false),
  ('ex-french-press',
  'French Press con Bilanciere EZ',
  'Braccia',
  'Tricipiti',
  ARRAY['Avambracci'],
  'Bilanciere',
  'weight_reps',
  'Sdraiati su panca. Abbassa il bilanciere verso la fronte o dietro la testa flettendo solo i gomiti e poi risali.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-performing-triceps-pushdown-at-the-gym-40335-large.mp4',
  false),
  ('ex-estensioni-sopra-testa',
  'Estensioni Tricipiti Sopra la Testa (Cavo)',
  'Braccia',
  'Tricipiti',
  ARRAY['Avambracci'],
  'Cavi',
  'weight_reps',
  'Dalle spalle inclinate in avanti, distendi le braccia sopra la testa enfatizzando il capo lungo del tricipite.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-performing-triceps-pushdown-at-the-gym-40335-large.mp4',
  false),
  ('ex-panca-stretta',
  'Panca Piana con Presa Stretta',
  'Braccia',
  'Tricipiti',
  ARRAY['Avambracci'],
  'Bilanciere',
  'weight_reps',
  'Presa alla larghezza delle spalle con gomiti vicini al torace per spostare il lavoro dal petto ai tricipiti.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-bench-press-with-barbell-close-up-40321-large.mp4',
  false),
  ('ex-wrist-curl',
  'Wrist Curl con Bilanciere (Flessione Polsi)',
  'Braccia',
  'Avambracci',
  ARRAY['Avambracci'],
  'Bilanciere',
  'weight_reps',
  'Avambracci poggiati sulle cosce o su una panca con i polsi liberi. Fletti i polsi sollevando il bilanciere.',
  'Tieni i gomiti bloccati vicino al busto, isolando completamente il muscolo target senza dondolare.',
  'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-man-doing-biceps-curls-with-dumbbells-40328-large.mp4',
  false),
  ('ex-squat',
  'Squat con Bilanciere (Back Squat)',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Bilanciere',
  'weight_reps',
  'Bilanciere sui trapezi, piedi larghezza spalle. Scendi spingendo il bacino indietro e le ginocchia in fuori oltre il parallelo.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-front-squat',
  'Front Squat con Bilanciere',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Bilanciere',
  'weight_reps',
  'Bilanciere poggiato sui deltoidi anteriori con gomiti alti. Il busto rimane molto eretto, isolando i quadricipiti.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-leg-press',
  'Leg Press a 45°',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Piedi a metà pedana larghezza spalle. Abbassa il carrello fino a 90° al ginocchio senza staccare il sacro dallo schienale.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-hack-squat',
  'Hack Squat alla Macchina',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Schiena aderente al supporto inclinato. Scendi in profondità per uno stimolo quadricipite massimale in sicurezza.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-leg-extension',
  'Leg Extension alla Macchina',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Siediti con ginocchia allineate al perno della macchina. Estendi le gambe fino al blocco orizzontale e controlla la discesa.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-affondi-manubri',
  'Affondi Camminati con Manubri',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Manubri',
  'weight_reps',
  'Fai un passo in avanti flettendo entrambe le ginocchia a 90°. Spingi con il tallone anteriore per fare il passo successivo.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-bulgarian-split-squat',
  'Split Squat Bulgaro con Manubri',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Manubri',
  'weight_reps',
  'Piede posteriore poggiato su una panca dietro di te. Scendi in verticale fino a sfiorare il terreno con il ginocchio dietro.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-goblet-squat',
  'Goblet Squat con Kettlebell',
  'Gambe',
  'Quadricipiti',
  ARRAY['Core', 'Glutei'],
  'Kettlebell',
  'weight_reps',
  'Tieni la kettlebell al petto per le corna. Scendi in squat profondo tenendo i gomiti tra le ginocchia.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-abductor-machine',
  'Abductor Machine (Glutei Esterni)',
  'Gambe',
  'Abduttori',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Siediti con cuscinetti esterni alle cosce. Allarga le gambe spingendo con i glutei e mantieni la massima apertura per 1 secondo.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-stacco-rumeno',
  'Stacco Rumeno con Bilanciere (RDL)',
  'Gambe',
  'Femorali',
  ARRAY['Core', 'Glutei'],
  'Bilanciere',
  'weight_reps',
  'Ginocchia semirigide. Spingi il bacino indietro mantenendo il bilanciere a contatto con le cosce per allungare i femorali.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-stacco-rumeno-manubri',
  'Stacco Rumeno con Manubri',
  'Gambe',
  'Femorali',
  ARRAY['Core', 'Glutei'],
  'Manubri',
  'weight_reps',
  'Fletti le anche indietro tenendo la colonna neutra. Scendi fino a metà tibia e risali contraendo glutei e femorali.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-leg-curl',
  'Leg Curl Seduto alla Macchina',
  'Gambe',
  'Femorali',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Cosce bloccate dal cuscinetto. Fletti le ginocchia portando i talloni sotto il sedile e controlla la fase negativa.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-leg-curl-sdraiato',
  'Leg Curl Sdraiato alla Macchina',
  'Gambe',
  'Femorali',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Sdraiati prono con il cuscinetto sopra i talloni. Tira i piedi verso i glutei senza sollevare il bacino dalla panca.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-calf-raise-piedi',
  'Calf Raise in Piedi alla Macchina',
  'Gambe',
  'Polpacci',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Punte sulla pedana e spalle sotto i cuscinetti. Scendi allungando il tendine e sollevati al massimo sulla punta dei piedi.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-calf-raise-seduto',
  'Calf Raise da Seduto alla Macchina',
  'Gambe',
  'Polpacci',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Ginocchia flesse a 90° sotto il cuscinetto per isolare il muscolo soleo. Massima estensione e pausa in contrazione.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-calf-press',
  'Calf Raise alla Leg Press',
  'Gambe',
  'Polpacci',
  ARRAY['Core', 'Glutei'],
  'Macchina',
  'weight_reps',
  'Punte sulla parte inferiore della pedana della leg press con gambe tese. Fletti ed estendi le caviglie controllando il carico.',
  'Piedi ben saldi a terra, spingi attraverso il mesopiede. Ginocchia sempre allineate con le punte dei piedi. Schiena neutra.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-cable-crunch',
  'Crunch al Cavo con Corda da Inginocchiati',
  'Core',
  'Addominali',
  ARRAY['Flessori anca', 'Lombari'],
  'Cavi',
  'weight_reps',
  'In ginocchio davanti al cavo alto. Tieni la corda ai lati della testa e fletti la gabbia toracica verso le ginocchia.',
  'Retroverti il bacino, attiva il pavimento pelvico e mantieni l''ombelico spinto verso la colonna vertebrale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-performing-abdominal-crunches-at-home-40319-large.mp4',
  false),
  ('ex-leg-raise-parallele',
  'Sollevamento Gambe alle Parallele',
  'Core',
  'Addominali',
  ARRAY['Flessori anca', 'Lombari'],
  'Niente',
  'weight_reps',
  'Avambracci appoggiati ai supporti della torre. Solleva le gambe tese o piegate fino a superare i 90° flettendo il bacino.',
  'Retroverti il bacino, attiva il pavimento pelvico e mantieni l''ombelico spinto verso la colonna vertebrale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-performing-abdominal-crunches-at-home-40319-large.mp4',
  false),
  ('ex-hanging-leg-raise',
  'Hanging Leg Raise alla Sbarra',
  'Core',
  'Addominali',
  ARRAY['Flessori anca', 'Lombari'],
  'Niente',
  'weight_reps',
  'Appeso alla sbarra per trazioni. Solleva le gambe tese fino alla sbarra contraendo con forza gli addominali bassi.',
  'Retroverti il bacino, attiva il pavimento pelvico e mantieni l''ombelico spinto verso la colonna vertebrale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-performing-abdominal-crunches-at-home-40319-large.mp4',
  false),
  ('ex-plank',
  'Plank Addominale Isometrico',
  'Core',
  'Addominali',
  ARRAY['Flessori anca', 'Lombari'],
  'Niente',
  'time_only',
  'Poggiati sugli avambracci e sulle punte dei piedi. Mantieni il corpo rigido come una tavola stringendo glutei e addome.',
  'Retroverti il bacino, attiva il pavimento pelvico e mantieni l''ombelico spinto verso la colonna vertebrale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-performing-abdominal-crunches-at-home-40319-large.mp4',
  false),
  ('ex-bicycle-crunch',
  'Gomiti sulle Ginocchia (Bicycle Crunch)',
  'Core',
  'Addominali',
  ARRAY['Flessori anca', 'Lombari'],
  'Niente',
  'weight_reps',
  'Sdraiato sulla schiena, alterna portando il gomito destro al ginocchio sinistro e viceversa per stimolare gli obliqui.',
  'Retroverti il bacino, attiva il pavimento pelvico e mantieni l''ombelico spinto verso la colonna vertebrale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-performing-abdominal-crunches-at-home-40319-large.mp4',
  false),
  ('ex-leg-raise-sdraiato',
  'Leg Raise Sdraiato su Tappetino',
  'Core',
  'Addominali',
  ARRAY['Flessori anca', 'Lombari'],
  'Niente',
  'weight_reps',
  'Mani sotto i glutei per proteggere la zona lombare. Solleva le gambe tese a 90° e scendi lentamente senza toccare il pavimento.',
  'Retroverti il bacino, attiva il pavimento pelvico e mantieni l''ombelico spinto verso la colonna vertebrale.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-performing-abdominal-crunches-at-home-40319-large.mp4',
  false),
  ('ex-tapis-roulant',
  'Tapis Roulant (Corsa o Camminata Inclinata)',
  'Cardio',
  'Cardio',
  ARRAY['Gambe', 'Polpacci', 'Cuore'],
  'Macchina',
  'distance_time',
  'Attività cardiovascolare aerobica. Mantieni una cadenza costante o sperimenta intervalli HIIT per massimizzare il consumo calorico.',
  'Postura eretta, spalle rilassate, respirazione ritmata e appoggio del piede morbido per preservare le articolazioni.',
  'https://assets.mixkit.co/videos/preview/mixkit-man-doing-bench-press-with-barbell-close-up-40321-large.mp4',
  false),
  ('ex-cyclette',
  'Cyclette / Spin Bike',
  'Cardio',
  'Cardio',
  ARRAY['Gambe', 'Polpacci', 'Cuore'],
  'Macchina',
  'distance_time',
  'Pedala a ritmo sostenuto regolando la resistenza magnetica per stimolare la capacità polmonare e le gambe senza impatto sulle articolazioni.',
  'Postura eretta, spalle rilassate, respirazione ritmata e appoggio del piede morbido per preservare le articolazioni.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-ellittica',
  'Ellittica (Cross Trainer)',
  'Cardio',
  'Cardio',
  ARRAY['Gambe', 'Polpacci', 'Cuore'],
  'Macchina',
  'distance_time',
  'Movimento fluido combinato braccia-gambe a basso impatto articolare per resistenza e consumo calorico.',
  'Postura eretta, spalle rilassate, respirazione ritmata e appoggio del piede morbido per preservare le articolazioni.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false),
  ('ex-salto-corda',
  'Salto della Corda (Jump Rope)',
  'Cardio',
  'Cardio',
  ARRAY['Gambe', 'Polpacci', 'Cuore'],
  'Niente',
  'time_only',
  'Rimbalza sulla punta dei piedi facendo ruotare la corda solo con i polsi, ritmo e coordinazione continui.',
  'Postura eretta, spalle rilassate, respirazione ritmata e appoggio del piede morbido per preservare le articolazioni.',
  'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-squats-with-a-barbell-40324-large.mp4',
  false)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  muscle_group = EXCLUDED.muscle_group,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  tracking_type = EXCLUDED.tracking_type,
  instructions = EXCLUDED.instructions,
  execution_tips = EXCLUDED.execution_tips,
  video_url = EXCLUDED.video_url,
  is_custom = false;

COMMIT;

-- Verifica immediata del corretto inserimento
SELECT count(*) AS total_exercises_seeded FROM public.exercises WHERE is_custom = false;
